# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mgNt1RpSx7xOpK-d5Xw8IGI26sLN2gGE
"""

n = int(input())
r = 0
mat = [1] * n


for  i  in  range(n):
    st = input()
    front, back = (int(a)  for  a  in  st.split())
    if  min(front, back) >=  0   and  front + back == n -  1:
        if  front < n  and  mat[front] !=  2:
            mat[front] = 2
            r += 1
print(r)